from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563d0c19ca00'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Schemas are created here rather than only in infra/postgres/init.sql
    # so `alembic upgrade head` is self-contained and works against any
    # fresh Postgres instance, not just one that already ran the compose
    # init script.
    op.execute("CREATE SCHEMA IF NOT EXISTS api")
    op.execute("CREATE SCHEMA IF NOT EXISTS inventory")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('attendee', 'organizer', 'admin', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_users_email'), 'users', ['email'], unique=True, schema='api')
    op.create_table('event_inventory',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='inventory'
    )
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['api.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_events_organizer_id'), 'events', ['organizer_id'], unique=False, schema='api')
    op.create_index(op.f('ix_api_events_starts_at'), 'events', ['starts_at'], unique=False, schema='api')
    op.create_index(op.f('ix_api_events_title'), 'events', ['title'], unique=False, schema='api')
    op.create_table('reservations',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'released', 'expired', name='reservation_status', native_enum=False, length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['inventory.event_inventory.event_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_reservations_event_id'), 'reservations', ['event_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'reservations', ['order_id'], unique=False, schema='inventory')
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='order_status', native_enum=False, length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['api.events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['api.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_orders_event_id'), 'orders', ['event_id'], unique=False, schema='api')
    op.create_index(op.f('ix_api_orders_user_id'), 'orders', ['user_id'], unique=False, schema='api')
    op.create_index('ix_orders_user_idempotency_key', 'orders', ['user_id', 'idempotency_key'], unique=True, schema='api', postgresql_where='idempotency_key IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_idempotency_key', table_name='orders', schema='api', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index(op.f('ix_api_orders_user_id'), table_name='orders', schema='api')
    op.drop_index(op.f('ix_api_orders_event_id'), table_name='orders', schema='api')
    op.drop_table('orders', schema='api')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='reservations', schema='inventory')
    op.drop_index(op.f('ix_inventory_reservations_event_id'), table_name='reservations', schema='inventory')
    op.drop_table('reservations', schema='inventory')
    op.drop_index(op.f('ix_api_events_title'), table_name='events', schema='api')
    op.drop_index(op.f('ix_api_events_starts_at'), table_name='events', schema='api')
    op.drop_index(op.f('ix_api_events_organizer_id'), table_name='events', schema='api')
    op.drop_table('events', schema='api')
    op.drop_table('event_inventory', schema='inventory')
    op.drop_index(op.f('ix_api_users_email'), table_name='users', schema='api')
    op.drop_table('users', schema='api')
    # ### end Alembic commands ###
